import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { ProductList } from '@/components/ProductList'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fortnite Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-blue-800 flex-1 pb-20">
        <Header />
        {/* <p className="font-cursive text-3xl text-white my-20 text-center">Fortnite Store</p> */}

        <div className='flex flex-col gap-10 mt-20'>
          <ProductList title='Mais procurados' />
          <ProductList title='Em destaque' />
        </div>
      </main>
      <Footer />
    </>
  )
}
